substitutions:
  timezone: Asia/Taipei
  default_city_name: 臺中市
  default_town_name: 南屯區
  default_api: CWA-E02B6C42-9A1B-4FD7-B5A6-BA605006274E
external_components:
  - source:
      type: git
      url: https://github.com/parkghost/esphome-cwa-town-forecast
      ref: main
    refresh: 0s
    components: [ cwa_town_forecast ]

logger:
  level: DEBUG

esphome:
  name: "auto-cwa-dual"
  friendly_name: "auto cwa dual"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - delay: 5s
    - script.execute: update_forecast_all

api:

sun:
  latitude: 24.153935542067238
  longitude: 120.63569437196482

ota:
  - platform: esphome

web_server:
  version: 3
  port: 80

debug:
  update_interval: 5s

time:
  - platform: sntp
    id: esp_time
    timezone: $timezone
    servers:
      - time1.google.com
      - time2.google.com
      - time3.google.com
    on_time:
      - cron: "0 /30 * * * *"
        then:
          if:
            condition:
              - wifi.connected:
              - time.has_time:
            then:
              - script.execute: update_forecast_3d

      - cron: "0 0 6,18 * * *"
        then:
          if:
            condition:
              - wifi.connected:
              - time.has_time:
            then:
              - script.execute: update_forecast_7d

globals:
  - id: town_forecast_3d_init
    type: bool
    initial_value: "false"

  - id: town_forecast_7d_init
    type: bool
    initial_value: "false"

cwa_town_forecast:
  - api_key: !lambda return id(cwa_api_key).state;
    id: town_forecast_3d
    city_name: !lambda return id(city_name).state;
    town_name: !lambda return id(town_name).state;
    mode: 3-DAYS
    time_to: 1d
    on_data_change:
      - lambda: |-
          id(town_forecast_3d_init) = true;


  - api_key: !lambda return id(cwa_api_key).state;
    id: town_forecast_7d
    city_name: !lambda return id(city_name).state;
    town_name: !lambda return id(town_name).state;
    mode: 7-DAYS
    on_data_change:
      - lambda: |-
          id(town_forecast_7d_init) = true;

select:
  - platform: template
    id: city_name
    name: City Name
    restore_value: true
    options:
      - "宜蘭縣"
      - "花蓮縣"
      - "臺東縣"
      - "澎湖縣"
      - "金門縣"
      - "連江縣"
      - "臺北市"
      - "新北市"
      - "桃園市"
      - "臺中市"
      - "臺南市"
      - "高雄市"
      - "基隆市"
      - "新竹縣"
      - "新竹市"
      - "苗栗縣"
      - "彰化縣"
      - "南投縣"
      - "雲林縣"
      - "嘉義縣"
      - "嘉義市"
      - "屏東縣"
    initial_option: $default_city_name
    optimistic: true
    entity_category: "config"

text:
  - platform: template
    id: town_name
    name: "Town Name"
    optimistic: true
    min_length: 0
    max_length: 20
    mode: text
    restore_value: true
    initial_value: $default_town_name
    entity_category: "config"

  - platform: template
    id: cwa_api_key
    name: "CWA API Key"
    optimistic: true
    min_length: 0
    max_length: 42
    mode: text
    restore_value: true
    initial_value: $default_api
    entity_category: "config"    

button:
  - platform: template
    name: "Update Forecast 3D"
    on_press:
      - script.execute: update_forecast_3d

  - platform: template
    name: "Update Forecast 7D"
    on_press:
      - script.execute: update_forecast_7d

  - platform: template
    name: "Update Forecast"
    on_press:
      - script.wait: update_forecast_3d
      - script.execute: update_forecast_3d
      - script.wait: update_forecast_7d
      - script.execute: update_forecast_7d

  - platform: template
    name: "Dump Forcast 3D Data"
    on_press:
      - lambda: |-
          id(town_forecast_3d)->get_data().dump();

  - platform: template
    name: "Dump Forcast 7D Data"
    on_press:
      - lambda: |-
          id(town_forecast_7d)->get_data().dump();

  - platform: template
    name: "Analyze Forcast Data"
    on_press:
      - script.execute: analyze_data

sensor:
  - platform: cwa_town_forecast
    cwa_town_forecast_id: town_forecast_3d
    temperature:
      name: "3D Temperature"
      id: d3_temperature
      accuracy_decimals: 0
    dew_point:
      name: "3D Dew Point"
      id: d3_dew_Point
      accuracy_decimals: 0
    apparent_temperature:
      name: "3D Apparent Temperature"
      id: d3_apparent_temperature
      accuracy_decimals: 0
    relative_humidity:
      name: "3D Relative Humidity"
      id: d3_relative_humidity
      accuracy_decimals: 0
    wind_speed:
      name: "3D Wind Speed"
      id: d3_wind_speed
      accuracy_decimals: 0
    probability_of_precipitation:
      name: "3D Probability Of Precipitation (3H)"
      id: d3_probability_of_precipitation_3h
  - platform: cwa_town_forecast
    cwa_town_forecast_id: town_forecast_7d
    temperature:
      name: "7D Avg Temperature"
      id: d7_avg_temperature
      accuracy_decimals: 0
    max_temperature:
      name: "7D Max Temperature"
      id: d7_max_temperature
      accuracy_decimals: 0
    min_temperature:
      name: "7D Min Temperature"
      id: d7_min_temperature
      accuracy_decimals: 0
    dew_point:
      name: "7D Avg Dew Point"
      id: d7_avg_dew_point
      accuracy_decimals: 0
    relative_humidity:
      name: "7D Relative Humidity"
      id: d7_relative_humidity
      accuracy_decimals: 0
    max_apparent_temperature:
      name: "7D Max Apparent Temperature"
      id: d7_max_apparent_temperature
      accuracy_decimals: 0
    min_apparent_temperature:
      name: "7D Min Apparent Temperature"
      id: d7_min_apparent_temperature
      accuracy_decimals: 0
    wind_speed:
      name: "7D Wind Speed"
      id: d7_win_speed
      accuracy_decimals: 0
    probability_of_precipitation:
      name: "7D Probability Of Precipitation (12H)"
      id: d7_probability_of_precipitation_12h
    uv_index:
      name: "7D UV Index"
      id: d7_uv_index
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    # psram:
    #   name: "Free PSRAM"

text_sensor:
  - platform: cwa_town_forecast
    cwa_town_forecast_id: town_forecast_3d
    comfort_index:
      name: "3D Comfort Index"
      id: d3_comfort_index
    comfort_index_description:
      name: "3D Comfort Index Description"
      id: d3_comfort_index_description
    weather:
      name: "3D Weather"
      id: d3_weather
    weather_code:
      name: "3D Weather Code"
      id: d3_weather_code
    weather_description:
      name: "3D Weather Description"
      id: d3_weather_description
    weather_icon:
      name: "3D Weather Icon"
      id: d3_weather_icon
    wind_direction:
      name: "3D Wind Direction"
      id: d3_wind_direction
    beaufort_scale:
      name: "3D Beaufort Scale"
      id: d3_beaufort_scale
    city:
      name: "3D City"
      id: d3_city
    town:
      name: "3D Town"
      id: d3_town
    last_updated:
      name: "3D Last Updated"
      id: d3_last_updated

  - platform: cwa_town_forecast
    cwa_town_forecast_id: town_forecast_7d
    max_comfort_index:
      name: "7D Max Comfort Index"
      id: d7_max_comfort_index
    min_comfort_index:
      name: "7D Min Comfort Index"
      id: d7_min_comfort_index
    max_comfort_index_description:
      name: "7D Max Comfort Index Description"
      id: d7_max_comfort_index_description
    min_comfort_index_description:
      name: "7D Min Comfort Index Description"
      id: d7_min_comfort_index_description
    wind_direction:
      name: "7D Wind Direction"
      id: d7_wind_direction
    beaufort_scale:
      name: "7D Beaufort Scale"
      id: d7_beaufort_scale
    weather:
      name: "7D Weather"
      id: d7_weather
    weather_code:
      name: "7D Weather Code"
      id: d7_weather_code
    weather_icon:
      name: "7D Weather Icon"
      id: d7_weather_icon
    uv_exposure_level:
      name: "7D UV Exposure Level"
      id: d7_uv_exposure_level
    weather_description:
      name: "7D Weather Description"
      id: d7_weather_description
    city:
      name: "7D City"
      id: d7_city
    town:
      name: "7D Town"
      id: d7_town
    last_updated:
      name: "7D Last Updated"
      id: d7_last_updated

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

  - platform: template
    name: "Moon Phase"
    id: moon_phase
    update_interval: 5min
    lambda: |-
      auto now = id(esp_time).now();
      auto now_tm = now.to_c_tm();
      int year = now_tm.tm_year + 1900;
      int month = now_tm.tm_mon + 1;
      int day = now_tm.tm_mday;

      if (month < 3) {
        year--;
        month += 12;
      }
      month++;

      double c = 365.25 * year;
      double e = 30.6 * month;
      double jd = c + e + day - 694039.09;
      jd /= 29.5305882;
      double b = jd - floor(jd);
      double age = b * 29.5305882;

      if (age < 1.84566)
        return {"new_moon"};
      else if (age < 5.53699)
        return {"waxing_crescent"};
      else if (age < 9.22831)
        return {"first_quarter"};
      else if (age < 12.91963)
        return {"waxing_gibbous"};
      else if (age < 16.61096)
        return {"full_moon"};
      else if (age < 20.30228)
        return {"waning_gibbous"};
      else if (age < 23.99361)
        return {"last_quarter"};
      else if (age < 27.68493)
        return {"waning_crescent"};
      else
        return {"new_moon"};

  - platform: sun
    name: "Sunrise Time"
    id: sun_sunrise
    type: sunrise
    format: "%H:%M"

  - platform: sun
    name: "Sunset Time"
    id: sun_sunset
    type: sunset
    format: "%H:%M"

script:
  - id: update_forecast_3d
    then:
      - component.update: town_forecast_3d

  - id: update_forecast_7d
    then:
      - component.update: town_forecast_7d

  - id: update_forecast_all
    then:
      - script.execute: update_forecast_3d
      - script.wait: update_forecast_3d
      - script.execute: update_forecast_7d
      - script.wait: update_forecast_7d

  - id: analyze_data
    then:
      - lambda: |-
          using namespace cwa_town_forecast;
          if(!(id(town_forecast_3d_init) && id(town_forecast_7d_init))) {
            ESP_LOGW("forecast", "Forecast not initialized");
            return;
          }

          auto forecast_3d_data = id(town_forecast_3d).get_data();
          auto forecast_7d_data = id(town_forecast_7d).get_data();
          bool fallback = true;

          auto now = id(esp_time).now();
          if(!now.is_valid()){
            ESP_LOGW("forecast", "Current time is not valid");
            return;
          }

          ESP_LOGI("forecast", "Current time: %s", now.strftime("%Y-%m-%d %H:%M:%S").c_str());

          ESP_LOGI("forecast", "Current Forecast(Nearly 1-3 hours):");
          ESP_LOGI("forecast", "  LocationsName: %s", forecast_3d_data.locations_name.c_str());
          ESP_LOGI("forecast", "  LocationName: %s", forecast_3d_data.location_name.c_str());
          ESP_LOGI("forecast", "  Temperature: %s°C", forecast_3d_data.find_value(ElementValueKey::TEMPERATURE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Dew Point: %s°C", forecast_3d_data.find_value(ElementValueKey::DEW_POINT, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Apparent Temperature: %s°C", forecast_3d_data.find_value(ElementValueKey::APPARENT_TEMPERATURE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Comfort Index: %s", forecast_3d_data.find_value(ElementValueKey::COMFORT_INDEX, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Comfort Index Description: %s", forecast_3d_data.find_value(ElementValueKey::COMFORT_INDEX_DESCRIPTION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Relative Humidity: %s%%", forecast_3d_data.find_value(ElementValueKey::RELATIVE_HUMIDITY, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Wind Direction: %s", forecast_3d_data.find_value(ElementValueKey::WIND_DIRECTION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Wind Speed: %s m/s", forecast_3d_data.find_value(ElementValueKey::WIND_SPEED, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Beaufort Scale: %s", forecast_3d_data.find_value(ElementValueKey::BEAUFORT_SCALE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Probability Of Precipitation: %s%%", forecast_3d_data.find_value(ElementValueKey::PROBABILITY_OF_PRECIPITATION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather: %s", forecast_3d_data.find_value(ElementValueKey::WEATHER, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather Description: %s", forecast_3d_data.find_value(ElementValueKey::WEATHER_DESCRIPTION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather Code: %s", forecast_3d_data.find_value(ElementValueKey::WEATHER_CODE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather Icon: %s", forecast_3d_data.find_value(ElementValueKey::WEATHER_ICON, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "");

          ESP_LOGI("forecast", "Today's Forecast(From now until midnight):");
          std::tm start = mktm(now.year, now.month, now.day_of_month, 0, 0, 0);
          std::tm end = mktm(now.year, now.month, now.day_of_month, 23, 59, 59);
          auto min_max = forecast_3d_data.find_min_max_values(ElementValueKey::TEMPERATURE, start, end);
          ESP_LOGI("forecast", "  Temperature: %.0f-%.0f °C", min_max.first, min_max.second);
          min_max = forecast_3d_data.find_min_max_values(ElementValueKey::APPARENT_TEMPERATURE, start, end);
          ESP_LOGI("forecast", "  Apparent Temperature: %.0f-%.0f °C", min_max.first, min_max.second);
          min_max = forecast_3d_data.find_min_max_values(ElementValueKey::RELATIVE_HUMIDITY, start, end);
          ESP_LOGI("forecast", "  Relative Humidity: %.0f-%.0f %%", min_max.first, min_max.second);
          ESP_LOGI("forecast", "");

          // see https://www.cwa.gov.tw/V8/C/W/Town/Town.html?TID=6500300
          ESP_LOGI("forecast", "Current Forecast(Day/Night):");
          ESP_LOGI("forecast", "  LocationsName: %s", forecast_7d_data.locations_name.c_str());
          ESP_LOGI("forecast", "  LocationName: %s", forecast_7d_data.location_name.c_str());
          ESP_LOGI("forecast", "  Avg Temperature: %s°C", forecast_7d_data.find_value(ElementValueKey::TEMPERATURE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Avg Dew Point: %s°C", forecast_7d_data.find_value(ElementValueKey::DEW_POINT, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Avg Relative Humidity: %s%%", forecast_7d_data.find_value(ElementValueKey::RELATIVE_HUMIDITY, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Max Temperature: %s°C", forecast_7d_data.find_value(ElementValueKey::MAX_TEMPERATURE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Min Temperature: %s°C", forecast_7d_data.find_value(ElementValueKey::MIN_TEMPERATURE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Max Apparent Temperature: %s°C", forecast_7d_data.find_value(ElementValueKey::MAX_APPARENT_TEMPERATURE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Min Apparent Temperature: %s°C", forecast_7d_data.find_value(ElementValueKey::MIN_APPARENT_TEMPERATURE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Max Comfort Index: %s", forecast_7d_data.find_value(ElementValueKey::MAX_COMFORT_INDEX, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Min Comfort Index: %s", forecast_7d_data.find_value(ElementValueKey::MIN_COMFORT_INDEX, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Max Comfort Index Description: %s", forecast_7d_data.find_value(ElementValueKey::MAX_COMFORT_INDEX_DESCRIPTION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Min Comfort Index Description: %s", forecast_7d_data.find_value(ElementValueKey::MIN_COMFORT_INDEX_DESCRIPTION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Probability Of Precipitation: %s%%", forecast_7d_data.find_value(ElementValueKey::PROBABILITY_OF_PRECIPITATION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  UV Index: %s", forecast_7d_data.find_value(ElementValueKey::UV_INDEX, false, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  UV Exposure Level: %s", forecast_7d_data.find_value(ElementValueKey::UV_EXPOSURE_LEVEL, false, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather: %s", forecast_7d_data.find_value(ElementValueKey::WEATHER, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather Code: %s", forecast_7d_data.find_value(ElementValueKey::WEATHER_CODE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather Icon: %s", forecast_7d_data.find_value(ElementValueKey::WEATHER_ICON, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Weather Description: %s", forecast_7d_data.find_value(ElementValueKey::WEATHER_DESCRIPTION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Wind Direction: %s", forecast_7d_data.find_value(ElementValueKey::WIND_DIRECTION, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Wind Speed: %s m/s", forecast_7d_data.find_value(ElementValueKey::WIND_SPEED, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "  Beaufort Scale: %s", forecast_7d_data.find_value(ElementValueKey::BEAUFORT_SCALE, fallback, now.to_c_tm()).c_str());
          ESP_LOGI("forecast", "");

          // see https://www.cwa.gov.tw/V8/C/W/Town/Town.html?TID=6500300
          ESP_LOGI("forecast", "7-Day Forecast(Day/Night):");
          {
            const auto &record = forecast_7d_data;
            auto now_tm = now.to_c_tm();
            for (int d = 0; d < 7; ++d) {
              // noon entry
              std::tm noon = now_tm;
              noon.tm_mday += d;
              noon.tm_hour = 12; noon.tm_min = 0; noon.tm_sec = 0;
              std::mktime(&noon);
              auto esp_noon = tm_to_esptime(noon);
              auto date_str = esp_noon.strftime("%Y-%m-%d");
              auto weekday = esp_noon.strftime("%a");
              std::string min_val = record.find_value(ElementValueKey::MIN_TEMPERATURE, false, noon);
              std::string max_val = record.find_value(ElementValueKey::MAX_TEMPERATURE, false, noon);
              std::string min_appa = record.find_value(ElementValueKey::MIN_APPARENT_TEMPERATURE, false, noon);
              std::string max_appa = record.find_value(ElementValueKey::MAX_APPARENT_TEMPERATURE, false, noon);              
              std::string icon = record.find_value(ElementValueKey::WEATHER_ICON, false, noon);
              std::string rain = record.find_value(ElementValueKey::PROBABILITY_OF_PRECIPITATION, false, noon);
              ESP_LOGI("forecast", "  %s %s %s: icon %s, rain %s%%, min %s°C, max %s°C, min_appa %s°C, max_appa %s°C",
                       date_str.c_str(),weekday.c_str(),  "(Day)  ", icon.c_str(), rain.c_str(), min_val.c_str(), max_val.c_str(),  min_appa.c_str(), max_appa.c_str());

            }
          }
